project_id = "uemxacekhtyvmmcuzhef"

[functions.send-invite]
verify_jwt = false

[functions.assistente-virtual]
verify_jwt = false

[functions.get-bacen-rate]
verify_jwt = false

[functions.consultar-taxa-bacen-sgs]
verify_jwt = false
