-- ETAPA 2: Nova Arquitetura de Dados - Tabela Única para Taxas BACEN
-- Esta tabela consolida as 48 séries oficiais de taxas de juros do BACEN

CREATE TABLE IF NOT EXISTS public.taxas_juros_bacen (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_serie INT NOT NULL,
  nome_modalidade TEXT NOT NULL,
  categoria TEXT NOT NULL, -- 'Pessoas Jurídicas' ou 'Pessoas Físicas'
  sub_categoria TEXT NOT NULL, -- Ex: 'Crédito Pessoal', 'Capital de Giro', 'Cartão de Crédito'
  data_referencia DATE NOT NULL,
  taxa_mensal DECIMAL(10, 4) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Garante que não haverá duplicidade de taxa para a mesma série no mesmo dia
  CONSTRAINT unique_serie_data UNIQUE (codigo_serie, data_referencia)
);

-- Índices para otimização de consultas rápidas
CREATE INDEX IF NOT EXISTS idx_taxas_bacen_serie_data 
  ON public.taxas_juros_bacen (codigo_serie, data_referencia DESC);

CREATE INDEX IF NOT EXISTS idx_taxas_bacen_categoria 
  ON public.taxas_juros_bacen (categoria, sub_categoria);

CREATE INDEX IF NOT EXISTS idx_taxas_bacen_data_ref 
  ON public.taxas_juros_bacen (data_referencia DESC);

-- Habilitar Row Level Security
ALTER TABLE public.taxas_juros_bacen ENABLE ROW LEVEL SECURITY;

-- Política: Acesso público de leitura (dados públicos do BACEN)
CREATE POLICY "Public read access for bacen rates" 
  ON public.taxas_juros_bacen
  FOR SELECT 
  USING (true);

-- Política: Apenas admins podem inserir/atualizar taxas
CREATE POLICY "Admins can manage bacen rates" 
  ON public.taxas_juros_bacen
  FOR ALL 
  USING (is_admin(auth.uid()));

-- Comentários para documentação
COMMENT ON TABLE public.taxas_juros_bacen IS 'Armazena as 48 séries temporais oficiais de taxas de juros do BACEN com recursos livres';
COMMENT ON COLUMN public.taxas_juros_bacen.codigo_serie IS 'Código SGS da série temporal no sistema do BACEN (ex: 20714, 20715, etc.)';
COMMENT ON COLUMN public.taxas_juros_bacen.nome_modalidade IS 'Nome completo da modalidade de crédito (ex: "Crédito pessoal não consignado - Total")';
COMMENT ON COLUMN public.taxas_juros_bacen.categoria IS 'Categoria principal: "Pessoas Jurídicas" ou "Pessoas Físicas"';
COMMENT ON COLUMN public.taxas_juros_bacen.sub_categoria IS 'Subcategoria da modalidade (ex: "Crédito Pessoal", "Capital de Giro rotativo")';
COMMENT ON COLUMN public.taxas_juros_bacen.taxa_mensal IS 'Taxa de juros mensal em percentual (ex: 2.5 = 2,5% a.m.)';
COMMENT ON COLUMN public.taxas_juros_bacen.data_referencia IS 'Data de referência da taxa (primeiro dia do mês)';